name: sport
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  pinput: ^5.0.0
  card_swiper: ^3.0.1
  flutter_localization: ^0.2.0
  ai_barcode_scanner: ^5.1.1+2
  flutter_barcode_scanner: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  barcode_scan2: ^4.3.3
  qr_code_scanner: ^1.0.1
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.2.2
  url_launcher: ^6.3.0
  loading_animation_widget: ^1.2.1
  shimmer: ^3.0.0
  fluttertoast: ^8.2.8
  flutter_styled_toast: ^2.2.1
  share_plus: ^10.0.0
  page_transition: ^2.1.0
  animations: ^2.0.11
  splash_view: ^2.0.1
  flutter_bloc: ^8.1.6
  carousel_slider: ^5.0.0
  equatable: ^2.0.5
  percent_indicator: ^4.2.3
  mockito: ^5.0.16
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.2.3
  get: ^4.6.6
  bloc: ^8.1.4

  calendar_date_picker2: ^1.1.5
  google_fonts: ^6.2.1
  flutter_lints: ^3.0.0
  connectivity_plus: ^2.2.2




flutter:
  uses-material-design: true

  assets:
    - assets/photos/
    - assets/icons/
