name: iOS-ipa-build

on:
  push:
    branches:
      - main

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Install Dependencies
        run: flutter pub get

      - name: Update CocoaPods
        run: sudo gem install cocoapods

      - name: Update Pod Repo
        run: pod repo update
        working-directory: ios

      # Update nanopb to resolve version conflicts
      - name: Update Specific Pods
        run: |
          pod update nanopb
          pod update GoogleUtilities/UserDefaults
        working-directory: ios

      - name: Install Pods
        run: pod install --repo-update
        working-directory: ios

      - name: Build iOS App
        run: flutter build ios --release --no-codesign --target=lib/main.dart

      - name: Prepare IPA for Export
        run: |
          mkdir Payload
          mv build/ios/iphoneos/Runner.app Payload/
          zip -qq -r FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload IPA to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is the first release"
