name: iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ios:
    name: Build iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod repo update

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Build iOS
        env:
          CI: true
        run: |
          flutter build ios --no-codesign

      - name: Archive Build
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath $PWD/build/Runner.xcarchive \
                     archive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
                     -archivePath $PWD/build/Runner.xcarchive \
                     -exportOptionsPlist ios/Runner/ExportOptions.plist \
                     -exportPath $PWD/build

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: ios-app
          path: build/Runner.ipa
